name: Build Python Package

on:
  workflow_run:
    workflows: ["Authenticate with Cloudsmith"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          pip install build

      - name: Build package
        run: |
          cd calculator-app/
          python -m build
          ls -l dist/   # verify output
      
      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/**
