name: Build and Publish Python Package to Cloudsmith

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  auth:
    runs-on: ubuntu-latest
    name: Authenticate with Cloudsmith
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate with Cloudsmith via OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          oidc-namespace: '${{ vars.CLOUDSMITH_NAMESPACE }}'
          oidc-service-slug: '${{ vars.CLOUDSMITH_SERVICE_SLUG }}'
          oidc-auth-only: 'true'
          
      - name: Save Cloudsmith Token
        run: |
          echo "CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY" >> $GITHUB_ENV
          
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and Publish Python Package
    needs: auth
    steps:
      - name: Authenticate with Cloudsmith via OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          oidc-namespace: '${{ vars.CLOUDSMITH_NAMESPACE }}'
          oidc-service-slug: '${{ vars.CLOUDSMITH_SERVICE_SLUG }}'
          oidc-auth-only: 'false'
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: pip install build

      - name: Build package
        run: |
          cd calculator-app
          python -m build
          ls -l dist/

      - name: Publish wheel (.whl) to Cloudsmith
        uses: cloudsmith-io/action@v0.5.3
        with:
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "python"
          owner: "${{ vars.CLOUDSMITH_NAMESPACE }}"
          repo: "${{ vars.CLOUDSMITH_REPO }}"
          file: "calculator-app/dist/*.whl"
          republish: "true"

      - name: Publish source distribution (.tar.gz) to Cloudsmith
        uses: cloudsmith-io/action@v0.5.3
        with:
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "python"
          owner: "${{ vars.CLOUDSMITH_NAMESPACE }}"
          repo: "${{ vars.CLOUDSMITH_REPO }}"
          file: "calculator-app/dist/*.tar.gz"
          republish: "true"
