name: Build and Publish Python Package to Cloudsmith

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  auth:
    runs-on: ubuntu-latest
    name: Authenticate with Cloudsmith
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate with Cloudsmith via OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          oidc-namespace: '${{ vars.CLOUDSMITH_NAMESPACE }}'
          oidc-service-slug: '${{ vars.CLOUDSMITH_SERVICE_SLUG }}'
          oidc-auth-only: 'true'
          
      - name: Save Cloudsmith Token
        run: |
          echo "CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY" >> $GITHUB_ENV

  build:
    runs-on: ubuntu-latest
    name: Build Python package
    needs: auth
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: pip install build

      - name: Build package
        run: |
          cd calculator-app
          python -m build
          ls -l dist/

      - name: Find Package Files
        run: |
          cd calculator-app/dist
          echo "WHEEL_FILE=$(ls *.whl)" >> $GITHUB_ENV
          echo "SDIST_FILE=$(ls *.tar.gz)" >> $GITHUB_ENV
          echo "Discovered wheel: $WHEEL_FILE"
          echo "Discovered sdist: $SDIST_FILE"

  publish-whl:
    runs-on: ubuntu-latest
    name: Publish Python Wheel to Cloudsmith
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish wheel
        uses: cloudsmith-io/action@v0.5.3
        with:
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "python"
          owner: "${{ vars.CLOUDSMITH_NAMESPACE }}"
          repo: "${{ vars.CLOUDSMITH_REPO }}"
          file: "calculator-app/dist/${{ env.WHEEL_FILE }}"
          republish: "true"

  publish-tar:
    runs-on: ubuntu-latest
    name: Publish Python Source Distribution to Cloudsmith
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish sdist
        uses: cloudsmith-io/action@v0.5.3
        with:
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "python"
          owner: "${{ vars.CLOUDSMITH_NAMESPACE }}"
          repo: "${{ vars.CLOUDSMITH_REPO }}"
          file: "calculator-app/dist/${{ env.SDIST_FILE }}"
          republish: "true"
